exports.dataDog = [
    {
        "raza":"pequeño",
        "pesoMin":1,
        "pesoMax":5,
        "edad":[
            {
                "edadMin":0,
                "edadMax":3,
                "rationDiary":90,
                "portionDiary":4
            },
            {
                "edadMin":3,
                "edadMax":6,
                "rationDiary":105,
                "portionDiary":3
            },
            {
                "edadMin":6,
                "edadMax":null,
                "rationDiary":120,
                "portionDiary":2
            }
        ]
    },
    {
        "raza":"middle",
        "pesoMin":5,
        "pesoMax":15,
        "edad":[
            {
                "edadMin":0,
                "edadMax":3,
                "rationDiary":90,
                "portionDiary":4
            },
            {
                "edadMin":3,
                "edadMax":6,
                "rationDiary":105,
                "portionDiary":3
            },
            {
                "edadMin":6,
                "edadMax":1000000000000,
                "rationDiary":120,
                "portionDiary":2
            }
        ]
    },
    {
        "raza":"big",
        "pesoMin":1,
        "pesoMax":5,
        "edad":[
            {
                "edadMin":0,
                "edadMax":3,
                "rationDiary":90,
                "portionDiary":4
            },
            {
                "edadMin":3,
                "edadMax":6,
                "rationDiary":105,
                "portionDiary":3
            },
            {
                "edadMin":6,
                "edadMax":null,
                "rationDiary":120,
                "portionDiary":2
            }
        ]
    }
]