###Test
GET https://server-pettrainer.herokuapp.com/api/petTraining

###Crear producto servidor
POST https://server-pettrainer.herokuapp.com/api/petTraining
Content-Type: application/json

{
    "code":1,
    "status":false,
    "Pet":"Pet",
    "WeightPet":1,
    "Configuration":0,
    "BirthDay":"11 14 2021"
}

###Update Raciones y cantidad
PUT http://localhost:4000/api/petTraining/
Content-Type: application/json

{
    "FoodDiary":"190,225,260",
    "RationsDiary":"4,3,2"
}

###Eliminar producto servidor
DELETE  http://localhost:4000/api/petTraining/6190acc95495110aacae0ec8

###ESP32
GET https://server-pettrainer.herokuapp.com/api/petTraining/61915a95d16ba4a624e033dc


###AppCel
PUT http://localhost:4000/api/petTraining/6190acc95495110aacae0ec8
Content-Type: application/json

{
    "Pet":"Dog",
    "WeightPet":13,
    "Configuration":1,
    "BirthDay":"7 15 2021"
}
###ESP32
PUT  http://localhost:4000/api/petTraining/
Content-Type: application/json

{
    "status":"true"
}
